apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-proxy-operator
subjects:
  - kind: ServiceAccount
    name: service-proxy-operator
    namespace: "{{ NAMESPACE }}"
roleRef:
  kind: ClusterRole
  name: service-proxy-operator
  apiGroup: rbac.authorization.k8s.io
