apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-proxy-operator
  namespace: "{{ NAMESPACE }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: service-proxy-operator
  template:
    metadata:
      labels:
        name: service-proxy-operator
    spec:
      serviceAccountName: service-proxy-operator
      containers:
        - name: service-proxy-operator
          image: "4m3ndy/service-proxy:v0.1.0"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "service-proxy-operator"
